# app/repositories/assignment.py
from typing import Protocol, runtime_checkable, Sequence, Optional
from app.schemas.assignment import Assignment, AssignmentCreate

@runtime_checkable
class AssignmentRepo(Protocol):
    async def create(self, data: AssignmentCreate, *, teacher_id: str) -> str: ...
    async def find_for_teacher(self, teacher_id: str) -> Sequence[Assignment]: ...
    async def find_for_student(self, student_id: str) -> Sequence[Assignment]: ...
    async def find_one(self, assignment_id: str) -> Optional[Assignment]: ...
    async def delete(self, assignment_id: str) -> bool: ...
